regions:
  - key: GA
    reddit_subs: [Atlanta, Georgia, Augusta, Savannah, assistance, food_pantry, mutualaid]
    mastodon_instances: ["https://mastodon.social"]
    youtube_queries:
      - 'Atlanta food distribution'
      - 'Georgia food bank distribution'
    rss_feeds: []
  - key: "Grand Rapids, MI"
    reddit_subs: [GrandRapids, Michigan, WestMichigan, assistance, food_pantry, mutualaid]
    mastodon_instances: ["https://mastodon.social"]
    youtube_queries:
      - 'Grand Rapids food distribution'
      - 'West Michigan food bank distribution'
    rss_feeds: []
  - key: "West Michigan"
    reddit_subs: [WestMichigan, GrandRapids, Michigan, assistance, food_pantry, mutualaid]
    mastodon_instances: ["https://mastodon.social"]
    youtube_queries:
      - 'West Michigan food pantry'
      - 'Holland MI food distribution'
    rss_feeds: []
